# Spawn AWS EC2 instance
---
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: false
  vars:
    instance_name: kubernets
    number_of_instance: 1
    host_file: /home/vagrant/scripts/playbooks/ansible/aws_kubernetes/hosts
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: provision ec2 instance
    ec2: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      image: ami-0cfcdb69
      instance_type: t2.micro 
      region: "{{ aws_region }}"
      key_name: aws_ec2_key
      group: ansible-sg
      volumes:
        - device_name: /dev/sda1
          volume_size: 10
          delete_on_termination: true
      instance_tags:
        Name: "{{ instance_name }}"
      count: "{{ number_of_instance }}"
      state: present
    register: ec2

  - name: wait for ssh to come up
    wait_for:
      host: "{{ item.public_dns_name }}" 
      delay: 30
      port: 22
      timeout: 60
      state: started
    with_items: "{{ ec2.instances }}"
  
  - name: remove old dns name
    lineinfile:
      path: /home/vagrant/scripts/playbooks/ansible/aws_kubernetes/hosts 
      regexp: '^.*?\.compute.amazonaws\..*$'
      state: absent

  - name: add new dns name
    lineinfile:
      path: /home/vagrant/scripts/playbooks/ansible/aws_kubernetes/hosts
      insertafter: '^\[aws\]'
      line: "{{ item.public_dns_name }}"
    with_items: "{{ ec2.instances }}"

  - meta: refresh_inventory
